#!/bin/bash

# Script to fix iOS Simulator runtime issue
# Xcode 26.1.1 requires iOS 26.1 simulator runtime, but only 18.5 and 26.0 are available

echo "=========================================="
echo "iOS Simulator Runtime Fix"
echo "=========================================="
echo ""
echo "PROBLEM:"
echo "Xcode 26.1.1 has iOS SDK 26.1, but your simulators have iOS 18.5 and 26.0 runtimes."
echo "Xcode cannot find a matching iOS 26.1 simulator runtime."
echo ""
echo "SOLUTION 1: Download iOS 26.1 Simulator Runtime (Recommended)"
echo "----------------------------------------"
echo "1. Open Xcode"
echo "2. Go to Xcode > Settings (or Preferences on older versions)"
echo "3. Click on 'Platforms' or 'Components' tab"
echo "4. Find 'iOS 26.1 Simulator' in the list"
echo "5. Click the download button (cloud icon) next to it"
echo "6. Wait for download to complete (this may take several minutes)"
echo ""
echo "SOLUTION 2: Use iOS 18.5 Simulator (Workaround)"
echo "----------------------------------------"
echo "Run this command to use the iOS 18.5 simulator:"
echo "  flutter run -d 6B06816D-1DD5-4E2E-B4FB-341551967F59"
echo ""
echo "Or boot and use it:"
echo "  xcrun simctl boot 6B06816D-1DD5-4E2E-B4FB-341551967F59"
echo "  flutter run"
echo ""
echo "SOLUTION 3: Check Available Runtimes"
echo "----------------------------------------"
echo "To see all available simulator runtimes:"
echo "  xcrun simctl list runtimes"
echo ""
echo "To see all available simulators:"
echo "  xcrun simctl list devices available"

